# Generated by Django 3.2.4 on 2021-06-19 06:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0002_auto_20210617_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.IntegerField(choices=[(1, 'Tea cup'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Giant')]),
        ),
        migrations.AlterField(
            model_name='country',
            name='taxes_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Taxes Percentage'),
        ),
        migrations.AlterField(
            model_name='medicalspeciality',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
    ]
