# Generated by Django 3.2.4 on 2021-06-19 09:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0004_auto_20210619_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_url',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='logo'),
        ),
    ]
