# Generated by Django 3.2.4 on 2021-06-19 10:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0005_alter_brand_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
