# Generated by Django 3.2.4 on 2021-06-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0006_alter_brand_logo_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('name', 'species_id')},
        ),
    ]
