# Generated by Django 3.2.4 on 2021-06-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0007_alter_breed_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petfood',
            options={'verbose_name': 'Pet Food', 'verbose_name_plural': 'Pet Foods'},
        ),
    ]
