# Generated by Django 3.2.4 on 2021-06-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('flag', models.CharField(max_length=256, null=True, verbose_name='Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('city', models.CharField(max_length=30, verbose_name='Name')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('active', models.BooleanField(default=True, verbose_name='Activo?')),
                ('open_schedule', models.CharField(max_length=128, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.countries')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
    ]
