# Generated by Django 3.2.4 on 2021-06-06 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('flag', models.CharField(max_length=256, null=True, verbose_name='Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('city', models.CharField(max_length=30, verbose_name='Name')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, max_length=15, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, max_length=15, null=True, verbose_name='Longitude')),
                ('active', models.BooleanField(default=True, verbose_name='Activo?')),
                ('open_schedule', models.CharField(max_length=128, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='SMSMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[('Verification Code', 'Verification Code'), ('Reminder', 'Reminder'), ('Notification', 'Notification'), ('Marketing', 'Marketing')], verbose_name='Type')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('flag', models.CharField(max_length=256, null=True, verbose_name='Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Message',
                'db_table': 'sms_messages',
            },
        ),
        migrations.CreateModel(
            name='UserRolesLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.locations')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol por Local',
                'verbose_name_plural': 'Roles por Local',
                'db_table': 'userroles_locations',
            },
        ),
    ]
