# Generated by Django 3.2.4 on 2021-06-05 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroleslocations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locations',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.countries'),
        ),
        migrations.AddConstraint(
            model_name='userroleslocations',
            constraint=models.UniqueConstraint(fields=('location', 'user', 'role'), name='userroleslocation_index'),
        ),
    ]
