# Generated by Django 3.2.4 on 2021-06-17 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_data', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('email_verified', models.BooleanField(default=False, null=True, verbose_name='Email Validated?')),
                ('phone_number', models.CharField(default='-', max_length=16, null=True, verbose_name='Phone')),
                ('phone_number_verified', models.BooleanField(default=False, null=True, verbose_name='Phone Verified?')),
                ('profile_pic_url', models.CharField(default='', max_length=256, null=True, verbose_name='Profile Pic')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Blocked?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super Admin?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatate_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_data.country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
    ]
