# Generated by Django 3.2.4 on 2021-07-02 14:59

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_data', '0011_auto_20210626_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('email_validated', models.BooleanField(default=False, verbose_name='Email Validated')),
                ('phone_number', models.CharField(blank=True, max_length=24, null=True, verbose_name='Phone Number')),
                ('phone_validated', models.BooleanField(default=False, verbose_name='Phone Validated')),
                ('password', models.CharField(max_length=64)),
                ('profile_pic_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pic')),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], verbose_name='Gender')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='Birth Date')),
                ('profile_pic_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pic')),
                ('castrated', models.BooleanField(verbose_name='Castrated')),
                ('last_service', models.DateTimeField(blank=True, null=True, verbose_name='Last Service')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('admin_created', models.BooleanField(verbose_name='Admin Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin_updated', models.BooleanField(verbose_name='Admin Updated')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_data.breed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pets', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.customer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_pets', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_data.vet')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='PetMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.DecimalField(decimal_places=2, max_digits=6)),
                ('measure_unit', models.IntegerField(choices=[(1, 'Cans'), (2, 'Units'), (3, 'Grams'), (4, 'Pounds')])),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('lifetime_required', models.BooleanField(default=False)),
                ('details', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('admin_created', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin_updated', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pet_medications', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_data.petdrug')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.pet')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_pet_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Medication',
                'verbose_name_plural': 'Pet Medications',
                'db_table': 'pet_medications',
            },
        ),
        migrations.CreateModel(
            name='PetFeeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_per_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Times Per Day')),
                ('food_portion', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Food Portion')),
                ('measure_unit', models.IntegerField(choices=[(1, 'Cans'), (2, 'Units'), (3, 'Grams'), (4, 'Pounds')], verbose_name='Measure Unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('details', models.CharField(blank=True, max_length=512, null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('admin_created', models.BooleanField(verbose_name='Admin Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin_updated', models.BooleanField(verbose_name='Admin Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pet_feedings', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_data.petfood')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.pet')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_pet_feedings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Feeding',
                'verbose_name_plural': 'Pet Feedings',
                'db_table': 'pet_feedings',
            },
        ),
        migrations.CreateModel(
            name='PetBelonging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('belongings_type', models.IntegerField(choices=[(1, 'Toys'), (2, 'Clothes'), (3, 'Food'), (4, 'Drugs'), (5, 'Utensils')])),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.pet')),
            ],
            options={
                'verbose_name': 'Pet Belonging',
                'verbose_name_plural': 'Pet Belongings',
                'db_table': 'pet_belongings',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='ix_user_email'),
        ),
        migrations.AddIndex(
            model_name='petmedication',
            index=models.Index(fields=['pet_id', 'drug_id'], name='ix_pet_drug'),
        ),
        migrations.AlterUniqueTogether(
            name='petmedication',
            unique_together={('pet_id', 'drug_id')},
        ),
        migrations.AddIndex(
            model_name='petfeeding',
            index=models.Index(fields=['pet_id', 'food_id'], name='ix_pet_feed'),
        ),
        migrations.AlterUniqueTogether(
            name='petfeeding',
            unique_together={('pet_id', 'food_id')},
        ),
        migrations.AddIndex(
            model_name='petbelonging',
            index=models.Index(fields=['pet_id', 'name'], name='ix_belonging_name'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['name'], name='ix_pet_name'),
        ),
    ]
