# Generated by Django 3.2.4 on 2021-07-04 20:16

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_data', '0011_auto_20210626_0335'),
        ('customers_and_pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petbelonging',
            name='belongings_type',
            field=models.IntegerField(choices=[(1, 'Toys'), (2, 'Clothes'), (3, 'Food'), (4, 'Drugs'), (5, 'Utensils')], verbose_name='Belongigs Type'),
        ),
        migrations.AlterField(
            model_name='petbelonging',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='petbelonging',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
        migrations.AlterField(
            model_name='petbelonging',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='petmedication',
            name='admin_created',
            field=models.BooleanField(verbose_name='Admin Created'),
        ),
        migrations.AlterField(
            model_name='petmedication',
            name='admin_updated',
            field=models.BooleanField(verbose_name='Admin Updated'),
        ),
        migrations.AlterField(
            model_name='petmedication',
            name='details',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='petmedication',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='petmedication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='petmedication',
            name='lifetime_required',
            field=models.BooleanField(default=False, verbose_name='Lifetime Required'),
        ),
        migrations.AlterField(
            model_name='petmedication',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.CreateModel(
            name='PetVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('version', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Version')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('width', models.IntegerField(verbose_name='Width')),
                ('reference_type', models.IntegerField(choices=[(1, 'Medical Record'), (2, 'Pet Profule'), (3, 'Pet Activity')], verbose_name='Reference Type')),
                ('reference_id', models.IntegerField(verbose_name='Reference ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.pet')),
            ],
            options={
                'verbose_name': 'Pet Video',
                'verbose_name_plural': 'Pet Videos',
                'db_table': 'pet_videos',
            },
        ),
        migrations.CreateModel(
            name='PetMedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(verbose_name='Event ID')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('details', models.CharField(blank=True, max_length=512, null=True, verbose_name='Details')),
                ('has_files', models.NullBooleanField(verbose_name='Has Files')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('admin_created', models.BooleanField(verbose_name='Admin Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin_updated', models.BooleanField(verbose_name='Admin Updated')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_data.medicalaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pet_medical_records', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.pet')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_pet_medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Medical Record',
                'verbose_name_plural': 'Pet Medical Records',
                'db_table': 'pet_medical_records',
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('version', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Version')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('width', models.IntegerField(verbose_name='Width')),
                ('reference_type', models.IntegerField(choices=[(1, 'Medical Record'), (2, 'Pet Profule'), (3, 'Pet Activity')], verbose_name='Reference Type')),
                ('reference_id', models.IntegerField(verbose_name='Reference ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.pet')),
            ],
            options={
                'verbose_name': 'Pet Image',
                'verbose_name_plural': 'Pet Images',
                'db_table': 'pet_images',
            },
        ),
        migrations.AddIndex(
            model_name='petmedicalrecords',
            index=models.Index(fields=['pet_id', 'action_id'], name='ix_pet_med_action'),
        ),
    ]
