# Generated by Django 3.2.4 on 2021-07-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_and_pets', '0002_auto_20210704_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmedicalrecords',
            name='has_files',
            field=models.BooleanField(null=True, verbose_name='Has Files'),
        ),
    ]
