# Generated by Django 3.2.4 on 2021-07-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_and_pets', '0003_alter_petmedicalrecords_has_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='petvideo',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='Version'),
        ),
    ]
