# Generated by Django 3.2.4 on 2021-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_and_pets', '0007_auto_20210706_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmedication',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='petmedication',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
