# Generated by Django 3.2.4 on 2021-07-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_and_pets', '0008_auto_20210706_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmedicalrecords',
            name='event_date',
            field=models.DateField(verbose_name='Event Date'),
        ),
    ]
