# Generated by Django 3.2.4 on 2021-07-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0011_auto_20210626_0335'),
        ('customers_and_pets', '0009_alter_petmedicalrecords_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmedicalrecords',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_data.medicalevent'),
        ),
    ]
