# Generated by Django 3.2.4 on 2021-07-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_and_pets', '0010_alter_petmedicalrecords_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petvideo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='petvideo',
            name='width',
        ),
    ]
