# Generated by Django 3.2.4 on 2021-07-07 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers_and_pets', '0012_alter_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetMedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.CharField(max_length=10, verbose_name='Days of Week')),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hour')),
                ('minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Minute')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('admin_created', models.BooleanField(verbose_name='Admin Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin_updated', models.BooleanField(verbose_name='Admin Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pet_medication_schedules', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=models.Model, to='customers_and_pets.petmedication')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.pet')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_pet_medication_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Medication Schedule',
                'verbose_name_plural': 'Pet Medication Schedules',
                'db_table': 'pet_medication_schedules',
            },
        ),
        migrations.AddIndex(
            model_name='petmedicationschedule',
            index=models.Index(fields=['pet_id'], name='ix_medication_pet'),
        ),
    ]
