# Generated by Django 3.2.4 on 2021-07-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_and_pets', '0013_auto_20210707_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='petimage',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.petmedicalrecords'),
        ),
        migrations.AddField(
            model_name='petvideo',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.petmedicalrecords'),
        ),
        migrations.AlterField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.pet'),
        ),
        migrations.AlterField(
            model_name='petimage',
            name='reference_type',
            field=models.IntegerField(choices=[(1, 'Medical Record'), (2, 'Pet Profile'), (3, 'Pet Activity')], verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='petvideo',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers_and_pets.pet'),
        ),
        migrations.AlterField(
            model_name='petvideo',
            name='reference_type',
            field=models.IntegerField(choices=[(1, 'Medical Record'), (2, 'Pet Profile'), (3, 'Pet Activity')], verbose_name='Reference Type'),
        ),
    ]
