# Generated by Django 3.2.4 on 2021-06-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_locations', '0002_alter_openschedule_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='business_locations.location'),
        ),
    ]
