# Generated by Django 3.2.4 on 2021-06-26 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_locations', '0003_alter_hotelroom_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hotel_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='details',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='max_capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Max Capacity'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.IntegerField(choices=[(1, 'Regular Size'), (2, 'Large Size')], verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_hotel_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='openschedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_open_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='openschedule',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_open_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business_locations.location')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['location_id', 'user_id'], name='ix_location_roles'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('location_id', 'user_id')},
        ),
    ]
