# Generated by Django 3.2.4 on 2021-06-30 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_locations', '0005_auto_20210626_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business_locations.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='livestream_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Livestream Price'),
        ),
        migrations.AlterField(
            model_name='openschedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business_locations.location'),
        ),
    ]
