# Generated by Django 3.2.4 on 2021-06-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0011_auto_20210626_0335'),
        ('business_locations', '0006_auto_20210630_1354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together={('service_id', 'location_id', 'specie_id', 'pet_size')},
        ),
    ]
