# Generated by Django 3.2.4 on 2021-07-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_locations', '0007_alter_pricing_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='pet_size',
            field=models.IntegerField(choices=[(1, 'Tea cup'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Giant')], verbose_name='Pet Size'),
        ),
    ]
